### ISSUE TITLE
DarkVector renders without styles

### ISSUE THREAD

**Issue by jdlrobson** [dolfinus/DarkVector#12]
Skin::setupSkinUserCss() has been hard deprecated after being soft deprecated in 1.35. One of the side effects of this is that if not patched the skin will render without styles in 1.36

Please see https://phabricator.wikimedia.org/T266735 for how to fix this.

**Comment by dolfinus** [comment]
Hello.

Thank you for creating this issue.

Can you please check https://github.com/dolfinus/DarkVector/pull/13 whether is correct or not?

**Comment by dolfinus** [comment]
@jdlrobson, thanks!
