### ISSUE TITLE
`.background-image-svg()` is deprecated and is going to be removed in MW 1.36

### ISSUE THREAD

**Issue by Volker-E** [dolfinus/DarkVector#14]
See https://phabricator.wikimedia.org/T248062 for more information.

**Comment by dolfinus** [comment]
Hello.

Thank you for creating this issue.

Can you please review https://github.com/dolfinus/DarkVector/pull/15 ?

**Comment by Volker-E** [comment]
Seems reasonable just from the code. I assume the deleted SVGs are all not used anymore?

**Comment by dolfinus** [comment]
Yes, they are not used in any style.

Thanks!
