### ISSUE TITLE
Version Branches

### ISSUE THREAD

**Issue by MaxHayman** [dolfinus/DarkVector#16]
Hello,

can you make branches for the versions as your latest master commit doesnt support 1.31 

However going to https://github.com/dolfinus/DarkVector/commit/469a74300f998d26c47e7943e0dbaa5ed3d4103d it works. It seems that sometime after the 1.36 support it stopped working. As 1.31 and 1.36 are LTS versions can these be branched like other mediawiki content?

**Comment by dolfinus** [comment]
Hello.

I've created https://github.com/dolfinus/DarkVector/tree/mw-1.31 branch and updated skin info on MediaWiki, please check.
