### ISSUE TITLE
ExtensionRegistry error in mw 1.36-alpha

### ISSUE THREAD

**Issue by NachtRaben** [dolfinus/DarkVector#18]
I understand that this is an alpha release and may not be supported, but we are looking for a darker theme for our MW and hoping this will be a relatively easy issue to fix in a separate branch if necessary due to the alpha nature.

Issue will present itself when calling `wfLoadSkin('DarkVector');`

https://wiki.skyblockisles.com/index.php/Special:Version

```
Uncaught Exception: Unable to open file /var/www/mediawiki/skins/DarkVector/skin.json: 
filemtime(): stat failed for /var/www/mediawiki/skins/DarkVector/skin.json in /var/www/mediawiki/includes/registration/ExtensionRegistry.php:176
Stack trace:
#0 /var/www/mediawiki/includes/GlobalFunctions.php(89): ExtensionRegistry->queue('/var/www/mediaw...')
#1 /var/www/mediawiki/LocalSettings.php(130): wfLoadSkin('DarkVector')
#2 /var/www/mediawiki/includes/Setup.php(145): require_once('/var/www/mediaw...')
#3 /var/www/mediawiki/includes/WebStart.php(89): require_once('/var/www/mediaw...')
#4 /var/www/mediawiki/index.php(44): require('/var/www/mediaw...')
#5 {main}
  thrown in /var/www/mediawiki/includes/registration/ExtensionRegistry.php on line 176
  ```
  
![image](https://user-images.githubusercontent.com/4164436/108344505-348e0100-71ab-11eb-8d1b-0934622be0e2.png)

**Comment by dolfinus** [comment]
Hello.

Folder name should be exactly like the skin or extension name. Just rename VectorDark to DarkVector.

**Comment by NachtRaben** [comment]
Wow, that's what I get for doing this at 3am. Thanks for pointing that out!
