### ISSUE TITLE
Redlinks do not seem to render properly

### ISSUE THREAD

**Issue by copperwater** [dolfinus/DarkVector#19]
I'm an editor on a wiki that's recently added the darkvector skin. It doesn't look like red links (to nonexistent pages) render properly; they render the same orange as everything else, which makes browsing confusing. It looks like this is due to the !important in darkvector.less

https://github.com/dolfinus/DarkVector/blob/e981ba276bbdcecbe63b2b375802168b420be79d/darkvector.less#L235-L240

which overrides other styles on `a` elements. One can hack their way around this by editing MediaWiki:Darkvector.css with a `a.new { color:red !important }` or similar, but fighting !important with !important is a bad way to go about it.

I notice that darkvector.less already contains 

https://github.com/dolfinus/DarkVector/blob/e981ba276bbdcecbe63b2b375802168b420be79d/darkvector.less#L248-L251

but the !important on all `a` elements overrides this.

**Comment by dolfinus** [comment]
Hello.

I've made a change:
https://github.com/dolfinus/DarkVector/commit/25f94f170b70f5e33dbcef9e48a422efcd135a66

Could you try, please?

**Comment by copperwater** [comment]
Yes, this looks like it works now; redlinks are red by default without requiring any additional CSS in the mediawiki namespace.

**Comment by dolfinus** [comment]
Great, thank you!
