### ISSUE TITLE
 Deprecated: Use of User::isWatched was deprecated in MediaWiki 1.37.

### ISSUE THREAD

**Issue by jdlrobson** [dolfinus/DarkVector#24]
Seen on https://skins-demo.wmflabs.org/w/index.php?useskin=darkvector

```
 ! ) Deprecated: Use of User::isWatched was deprecated in MediaWiki 1.37. [Called from DarkVectorTemplate::execute in /vagrant/mediawiki/skins/DarkVector/DarkVectorTemplate.php at line 41] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 376
Call Stack
#TimeMemoryFunctionLocation
10.0002397880{main}(  ).../index.php:0
20.0039403680require( '/vagrant/mediawiki/index.php' ).../index.php:5
30.24875370000wfIndexMain(  ).../index.php:46
40.24885372128MediaWiki->run(  ).../index.php:53
50.24915372384MediaWiki->main(  ).../MediaWiki.php:559
60.60117245616MediaWiki::{closure:/vagrant/mediawiki/includes/MediaWiki.php:937-943}(  ).../MediaWiki.php:952
70.60117245616OutputPage->output(  ).../MediaWiki.php:939
80.63817419856SkinDarkVector->outputPage(  ).../OutputPage.php:2644
90.65457434256SkinDarkVector->generateHTML(  ).../SkinTemplate.php:147
100.98679389872DarkVectorTemplate->execute(  ).../SkinTemplate.php:132
110.98679389872User->isWatched(  ).../DarkVectorTemplate.php:41
120.98679389872wfDeprecated(  ).../User.php:3085
130.98679389872MWDebug::deprecated(  ).../GlobalFunctions.php:998
140.98689389968MWDebug::deprecatedMsg(  ).../MWDebug.php:230
150.98689391496MWDebug::sendRawDeprecated(  ).../MWDebug.php:352
160.98689391496trigger_error
(  ).../MWDebug.php:376
```

**Comment by dolfinus** [comment]
Hi.

Sorry for late response.
Unfortunately, I cannot check this fix because I'm still using MediaWiki 1.30. `WatchlistManager` there this method has been moved to was added in recent MediaWiki versions.

**Comment by jdlrobson** [comment]
I can confirm https://github.com/dolfinus/DarkVector/pull/25  fixes the issue with deprecations and fatals on master (1.38).

It should also work safely on 1.30, which hopefully you can confirm.

**Comment by dt192** [comment]
method_exists was returning true, so I was still getting the message. I had to comment out the whole if statement to fix it.

**Comment by jdlrobson** [comment]
That's expected and by design. The deprecation message is harmless. The patch fixes compatibility with version 1.38 (where it will break), while retaining support for existing versions ( < 1.37). I'm not sure if the latter is needed, but I wanted to err on the side of caution just in case.

 If you are just interested in making the warning go away you can do without any patch by disabling deprecation warnings using the instructions in https://www.mediawiki.org/wiki/Manual:How_to_debug#PHP_errors

e.g.

```
error_reporting( 0 );
ini_set( 'display_errors', 0);
```

**Comment by dt192** [comment]
Thanks for the replay.

The main isssue is that the message is diplayed floating over the page UI on all pages, making the theme unusable. It would be nice if it was a little more discreet.

I have done as you said and that has removed the warning.

Many thanks.

**Comment by jdlrobson** [comment]
> Thanks for the replay.
> 
> The main isssue is that the message is diplayed floating over the page UI on all pages, making the theme unusable. It would be nice if it was a little more discreet.
> 
> I have done as you said and that has removed the warning.
> 
> Many thanks.

Glad this worked out for you. Do you know how this got turned on? I'm wondering if it defaults to on in new installs which would not be great.
