### ISSUE TITLE
isWatched deprecated

### ISSUE THREAD

**Issue by Drxrey** [dolfinus/DarkVector#26]
Hi,

i really like this Skin, but I have an issue on mediawiki 1.37
![DarkVector issue](https://user-images.githubusercontent.com/83374044/151357944-10889813-d310-4a79-939a-6e80f5eebe6d.JPG)
.
What can I do?

thanks a lot

greeting
Eugene

**Comment by dolfinus** [comment]
Hello.

Could you please try this solution https://github.com/dolfinus/DarkVector/issues/24#issuecomment-1004447899 ?

**Comment by Drxrey** [comment]
hm ok, it´s only turn of the warning, i try this.

But i see just now an another issue:
![01](https://user-images.githubusercontent.com/83374044/151361715-54fb2ca6-44cb-49a9-a659-8f2dba6c8159.jpg)
![02](https://user-images.githubusercontent.com/83374044/151361725-7579cad5-cb3b-49a2-989a-eb53c1a68b1c.jpg)

The Toolbar for edit pages is really large with this skin.

**Comment by Drxrey** [comment]
addendum: the picture are white because i printet the page as pdf

**Comment by dolfinus** [comment]
Could you please give me a link to your MediaWiki installation to investigate this issue?

**Comment by Drxrey** [comment]
Hi, sorry for the late answer. My Wiki is not public, its only internal in my Company.

**Comment by dolfinus** [comment]
I cannot investigate this issue without access to a wiki

**Comment by jasonkhanlar** [comment]
I saw this related error in my error log too and searched and found https://gerrit.wikimedia.org/r/c/mediawiki/core/+/683444 which shows another project fixing the same issue. Maybe this skin can reproduce similar fix using WatchlistManager::isWatched?

**Comment by dolfinus** [comment]
The fix is already implemented, but new API is available only in MW 1.37 which was released only few months ago. I don't want to break backward compatibility with previous MW versions
