### ISSUE TITLE
Skin fataling in 1.39

### ISSUE THREAD

**Issue by jdlrobson** [dolfinus/DarkVector#30]
I'll provide a patch shortly!

**Comment by dolfinus** [comment]
Hi.

Could you please provide an example of error you've got?

**Comment by jdlrobson** [comment]
The construct method is not calling the parent [1]. The parent now sets various things including componentRegistry which is needed to render.
This results in a 500 and no rendering:
<img width="1438" alt="Screen Shot 2022-09-20 at 8 01 29 AM" src="https://user-images.githubusercontent.com/148752/191293554-0cb17d64-ba17-4321-8a50-505881cc9c90.png">
(for some reason nothing is showing up in my server logs.. something must be catching and swallowing the error in the 500 rendering)
Let me know if you have trouble reproducing. Here's an example: https://skins-demo.wmflabs.org/wiki/Main_Page?useskin=darkvector

The fix is in https://github.com/dolfinus/DarkVector/pull/31 along with fixes for the deprecation warnings, but the construct line is likely the most important to add.

[1] https://github.com/wikimedia/mediawiki/blob/master/includes/skins/Skin.php#L253
