### ISSUE TITLE
Removal of BaseTemplate::renderAfterPortlet

### ISSUE THREAD

**Issue by jdlrobson** [dolfinus/DarkVector#33]
In 1.40 this method will be removed and is a breaking change to DarkVector.
Please remove the call in the skin.

https://phabricator.wikimedia.org/T320350

**Comment by dolfinus** [comment]
This method is used only if `Skin` class does not have method `getAfterPortlet`, which is true only on MW versions less than 1.35:
https://github.com/dolfinus/DarkVector/blame/a51c239f8d23c7062d55fc39180782c5dcce71cd/DarkVectorTemplate.php#L349-L354

So there should not be any issues
