### ISSUE TITLE
 Undefined index: class in DarkVectorTemplate.php on line 63

### ISSUE THREAD

**Issue by paladox** [dolfinus/DarkVector#4]
Hi, im getting 

ErrorException from line 63 of /srv/mediawiki/w/skins/DarkVector/DarkVectorTemplate.php: PHP Notice: Undefined index: class
#0 /srv/mediawiki/w/skins/DarkVector/DarkVectorTemplate.php(63): MWExceptionHandler::handleError(integer, string, string, integer, array)
#1 /srv/mediawiki/w/includes/skins/SkinTemplate.php(251): DarkVectorTemplate->execute()
#2 /srv/mediawiki/w/includes/OutputPage.php(2388): SkinTemplate->outputPage()
#3 /srv/mediawiki/w/includes/MediaWiki.php(868): OutputPage->output(boolean)
#4 /srv/mediawiki/w/includes/MediaWiki.php(880): MediaWiki->{closure}()
#5 /srv/mediawiki/w/includes/MediaWiki.php(524): MediaWiki->main()
#6 /srv/mediawiki/w/index.php(42): MediaWiki->run()
#7 {main}

**Comment by dolfinus** [comment]
Let's try again.
https://github.com/dolfinus/DarkVector/commit/2b2fc7d3ac5ff50b4f48592c201245f0a9224209

**Comment by paladox** [comment]
Thanks!
