### ISSUE TITLE
Module jquery.tabIndex is deprecated

### ISSUE THREAD

**Issue by Krinkle** [dolfinus/DarkVector#6]
> The `jquery.tabIndex` module existed to help compute a low or high tab index on focusable elements on a page. In most cases this code was redundant. Lines of code involving `firstTabIndex()` or `lastTabIndex()` are often best removed entirely. The module is deprecated in MediaWiki 1.34.
> 
> ```js
> // Simply remove
> $("#searchInput").attr("tabindex",$(document).lastTabIndex()+1);
> ```

See also <https://www.mediawiki.org/wiki/ResourceLoader/Migration_guide_(users)#jquery.tabIndex>

**Comment by dolfinus** [comment]
Fixed in https://github.com/dolfinus/DarkVector/commit/ce2215729fb0bdd3f0cdd0ecc6684ad9ab8a628d.
