### ISSUE TITLE
"Jump to: navigation, search" no longer hidden at the top of pages

### ISSUE THREAD

**Issue by Doctologist** [dolfinus/DarkVector#9]
As noted at [this link](https://www.mediawiki.org/wiki/Topic:Vjbutw0p8w3agwz4), this section is no longer hidden by the skin. Additionally, it seems that "new page" or "broken" links no longer display as red but display as yellow/gold.

**Comment by dolfinus** [comment]
Hello.

Can you provide a screenshot, please?

**Comment by SanneSideUp** [comment]
I can confirm, that "Jump to: navigation, search" is displayed in the default skin, however I removed it on my wiki be removing lines 148 to 154 from my DarkVectorTemplate.php :
`<div id="jump-to-nav" class="mw-jump">
					<?php $this->msg( 'jumpto' ) ?>
					<a href="#mw-head"><?php
						$this->msg( 'jumptonavigation' )
					?></a><?php $this->msg( 'comma-separator' ) ?>
					<a href="#p-search"><?php $this->msg( 'jumptosearch' ) ?></a>
				</div>`

As for the the styling of the new page" or "broken" links, you can control that in darkvector.less you may want to get rid of the !important in line 135 or by providing other values in the the a.new and a:visited classes, if necessary enforcing them with !important

**Comment by Doctologist** [comment]
You can see the text just below the "Test Page" title.
![Screen Shot](https://user-images.githubusercontent.com/64864205/95438424-1e258e00-090b-11eb-8c53-499d76a1b54f.jpg)

**Comment by dolfinus** [comment]
OK, could you please also provide MW version? And it'll be great to send a link to Special:Version page of your wiki.

**Comment by dolfinus** [comment]
It looks like in the latest MW version some default styles were changed, and now `.mw-jump` class items are not hidden anymore.
I've fixed skin styles here: https://github.com/dolfinus/DarkVector/commit/b6b35d17b4db74ce8c4a41a8986e0dd66a2f7a38
Please try to install skin again.

**Comment by dolfinus** [comment]
Can anybody check, please?
